### ISSUE TITLE
Failed to build module 'OnMobileRBTSDK'

### ISSUE THREAD

**Issue by sudiptobd** [ONMO/OnMobileRBT#1]
Hi, while using your latest release '3.0.15' from cocoapods, it says your SDK was build using Apple Swift version 5.4.2. 
Please, release a new built using latest Swift Version 5.5.2.

FYI, your last release '3.0.14' was built using Swift 5.5 (which is supported in Xcode 13.1, but doesn't support XCode 13.2.1 ).

Logs -

XCode Version: 13.2.1 (13C100) and Swift Compiler Version 5.5.2
Compiler Error Message: Failed to build module 'OnMobileRBTSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.

XCode Version:  13.1 (13A1030d) and Swift Compiler Version 5.5.1
Compiler Error Message:  Failed to build module 'OnMobileRBTSDK'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)', while this compiler is 'Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)'). Please select a toolchain which matches the SDK.

Please, do necessary, and send me a notification (if possible) at sudipto@brainstation-23.com. 
Thanks in advance.

**Comment by nareshkommana** [comment]
Resolved in later versions, hence closing it.
